dist:
- trusty
script:
- gcc --version > data.txt
deploy:
  provider: s3
  access_key_id: AKIAJZ6AVD62H27QWMKA
  secret_access_key:
    secure: YkvNaIWrrGK+oUA57TGXjmcTb1uwmo/SFQq+pEYrL9l2jFqXuGN2rOq0AausfiSg2xvBmIjPdRlxxo4jwoQmFEUH3yf2FnUuHPtYolHyoEhIel50VpNuuCb6jeMoLoEsuT3c1feBj7OkWxfysklJ0rlP6Y1Diq0EW/LyK0XWNMut0rRsiLMoHAUSU7MW8fip0ElfcanJQj4dHhdqy+0rtWdeVwcbgX6u2oeRnAqkom1NGiZUmlX4K94LU6I2jaef7fAbhkJkhvM9QtrNUvisAOgQMLYiDgSXYZxbdR7sWvlrbK4IahaA1nYeykjAjyLLayPpKIjZARB3liOiVpmN1ebL90N2UhEWqoRRqg4Bg1pIwyNQqymP7x7IM/i/2KN8jX56LGrh7q4uzzf6y7uBLk85jcP7ewthsGpCO+u1PKMFu5iCG/zHV/OgPxb2AowONN7Dk7+VkQ8rn+lglVR5FT/hmarJooa5hdn3X8YG6oVG1ApCs7D72sfDIuVykvw0AfVMTD5SqLaa37VH2W5dNdV6Hx7uLcZNQ78nVot9rRXU/wLXPQotrOgJ5NZbDihsqU1Y6qglelnbzUR5rnDiM+ir8j8XtF7CIKwYhd5DSSgCGi5/l0UeDqMV+wrvCG0T70chwjjrvLCIn5k/CL0nOpZKn3hCrsEnDJ+10q0rUJM=
  bucket: lgtv-tokyo
  upload-dir: "${TRAVIS_BUILD_NUMBER}"
  acl: private
