language: c
env:
  global:
  - ARTIFACTS_REGION="ap-northeast-1"
  - ARTIFACTS_BUCKET="lgtv-tokyo"
  - secure: mmpka7Hjqu9EOjfoQaIgTkXrO0RGDBYyGiB2VTdLyPw1UHc2TlEkZ3t2gjzSmM5R3S+Nw2UNkSrsLezjcUuYzClFG7jRm/B+V+Xo33KnTCI2eRHlZaSX2X8o9x0axjD+OURv9KFDfELu6xUWm0pI1pv9UlF21BFGi8Cbnz9Cy+uq7NXygOV2Yhg5xkk3AbHS31IA0SYEVn+7OCwsy4gNqsn/n1stw2O8mzbe+SlJPnWhXzeHoHDw8M1ZG8d26D6C3dxvEJyA7vZWnk+jXeRYe5BKHaR27JqQhqhWi0l3i1oyU0lK45BWKmA/SsijxXRQH2DGI2AR+RVD8o6i92WtdWbWZJlGJfMzQQvb+mytDUbYtAwglNWURf/kBGH6h22q+6Hk7HxFb17ntZQ/FdeM/0D0N0tJGV2J382q1lSGZ47RMv9ltcXpMqlRwuZDK/mXlDBkhAB3k/CbAZsnyIENIgy+9XjcS69P5/B/2Fq9vlJ1pTi8tQwrv5QZxl1VNh5XfauvZxSSYZqjGBIk/GF+EUJDpXQZsLTdI+09WicIv/ox07DixYfMid+Mkgxgj4K+J1tkjNcV2mxY0Je3X1bDt+qWBnEw3eunEPZXVfqGSu4jW4IvXEo2uHFPZb1BR0CGohyqvpjxh1l5gy4UWoaBF0lOCD2k3ysxedgYuJg4lss=
  - secure: FK5KyVBo+T3ZpKUOWn52dY+WibsaRM9DT1wPMR07APPphEablFPhMfuow3QTpnJUN1ymrm5dbliG/erh7/6A6drhb04Nv+jVwOiQMFb3ypq6AieNFt+j9iTWDJEK5leFKhUIcBdNGPiVPf7wrgHrCWypPbgBoVIwiJ6DKUawy/czFaCTl5qhoFs0ETRSzwVOAKP6PZqmf2Gp629nFUYEeCaF3k3poKh+JIJHELx+SvGTFEeovMZ7ltjnNpqeL8YPUAzokl7ZP6wB+WeKD43BoPDBoHoCiZdWgMkgqmV3gf079/2W92L4mwJUqWiqK7BJ8I9MQ6ixSxigUoqy4C8GxsIaPHWVEzRNjkuFFwlNQK/L5OYkOs+lVxD72t+u/E6LYX+rJ8syFQFytVNcI9DXAH1aag+7WTQl3bGOmohHwbel6UCFNy+ly5TX8EvlLrFiosMSkP+bHDN4uT8VxZ9chFX1Bu+FIO/zOBJ3yqBZ7Y+hIecuaKFXKmGp7JZ058uNTIWvC9iqRkhz64ld2G5IZh4TuBIN4DNA3I8NiCfNLiSjrTzq1yNAtWGdtqMRtWTcy001k1H7xFIi/57Kd8v6vq8OufcFedBEexvgFgP8ITN7c6zDCUG1NOZxrFei66+UuUjWv72JXOtPqRGwvJzwVPD/S7PaQuNbBcXAhreP4tU=
jobs:
  include:
  - stage: test
    script: echo "Start a buid"
  - stage: download
    script: 
    - wget https://dev.mysql.com/get/Downloads/MySQL-5.7/mysql-5.7.20.tar.gz 2>/dev/null 
    - mkdir temp
    - tar C temp/ -xzf mysql-5.7.20.tar.gz 2>/dev/null
    addons:
      artifacts:
        paths:
        - mysql-5.7.20.tar.gz
  - 
    script: 
    - wget http://mirror.navercorp.com/apache/tomcat/tomcat-8/v8.5.23/src/apache-tomcat-8.5.23-src.tar.gz 2>/dev/null
    - mkdir temp
    - tar C temp/ -xzf apache-tomcat-8.5.23-src.tar.gz 2>/dev/null
    addons:
      artifacts:
        paths:
        - apache-tomcat-8.5.23-src.tar.gz
  - stage: end
    script: echo "End"
