language: c
env:
  global:
  - ARTIFACTS_REGION="ap-northeast-1"
script: 
    - wget https://dev.mysql.com/get/Downloads/MySQL-5.7/mysql-5.7.20.tar.gz && tar -xzf mysql-5.7.20.tar.gz && pushd mysql-5.7.20/ && pwd
    - echo ${ARTIFACTS_KEY}
addons:
  artifacts:
    bucket: lgtv-tokyo
    key:
      secure: Sgbrjq0/9kH6kfmP1BxYDEVDDj7V56nMi1tXJNSU9mtFtR2jCfCBS4eAWduHAwQv6XiLP0/Kv/LI/my5R6w8Y7y6LI3j8PjFgHITlJSDidls2XDfawnNyKTU+r4Y1eM5JeRGCxu0tKUndZR/D7EN1JkQbiVNPL0Ear2sU6/mJPttkyLlWMAf22V8qBKbHbVut7zcGjxLJndDOYSRSB87JF7u0Ndls519qyhx0X6omz49Q16L5nBFzdSlsrKKpRbryh6gVBmwY+KVMnKPEGr48i6Ftek3SUVTN9qMaiEPU+5PvRlTe498LRGhFic7oeQRfjasLV/94cmcaGQWkYCDNdooGznmcLUPy+61N562YH1ML1a63/3xQHQtpbGjfguH1Wd9wxC+u7fBrVM5mu5PLEzCWy+mgzGaU7a+QUaiD9YeAKVGffwfWzIw5cs/ziLpZZsz3bYoJXY8/1fpSFvvjpDviTbx8gKslLQvN12jvoHUXtbWbUE68n4VTXfJ7miBYSN8frjsxUTziOcFEYyJtIzxPqYPfLhKEiywcG0DierYADcL0cN1wUI1SgVsqZg83HTf/g07r9f3LWSd/LtyFMqlAZUhLQMe6rg/h0hMiYzSfxVxFNtDCjypIfIYJNhoaRCQwoI/SJW1qn0uj4NKOUjoDV/WNyeWkLc/iJR8I0k=
    secret:
      secure: v4aJRZZf8HbNvtaLREmQaWzEJrCgwVi8/aiO588Nel5/PA3JUD6xuWz2HcJiE0OIXKAnYTmSv0XSqwaP1fJ5fDdseporuBDfCmycDzY1O+QBS+CApi2hwHivZ3yUFWNd2aOJpcOGvgWl09mGZb9pE5/WRsHOMLG7ZcpyBIdAUmyfcHbhKUVbCmhIBk9rsWFqR2Kg61AUOgpXDVl+2SNsYMsDxMhwHky4xa8ynWdlabIkJYAxc2S5/oUjtmHGotECEJM2Td2IrnVxz+BXHBh4JQOouC0UomfPDbV+0g+YVXFPuk5kgtnznnCw9HqM7X8icNOzfR9uxQ7D4r8AxqoViFuoqW1+qZjN10IuwurqiA3m5HzIFjDHAVBLOrWsqJJNl/J13rWJ2kSPnG0ou6+Gwg3ZWl92KPfHeyaukdPgTdJIoeApOVZKOC4BEOrjqGMghgiHf+wU+8vFrkhtiJPl8HBqowgVuXyL6S70DXrBk9GzPnKthR+qik43jjkZk8h8hZNzQTOKu6asOlWkkJnKJ4Ag5y+7lSTKPcxUzWPIqi40GMaWKMVWx2g9mlt8Bz/g72k1cTNlvP7ZKDmsKZhqcZYMftKmqCXE9DnUN9A9wTCYwpVWTFA/HvD4zcXd2Brjg7rNLfO/4zRBETSANovUyJdhYbn8nfXr7TuKJmPdnyI=
    paths:
    - mysql-5.7.20.tar.gz
