language: java
script:
- wget https://services.gradle.org/distributions/gradle-3.1-bin.zip && 
  unzip gradle-3.1-bin.zip && pushd gradle-3.1/bin && export PATH=$(pwd):${PATH} &&
  which gradle &&  popd &&
  wget http://apache.mirror.cdnetworks.com/aurora/0.18.0/apache-aurora-0.18.0.tar.gz &&
  tar xvzf apache-aurora-0.18.0.tar.gz &&
  pushd apache-aurora-0.18.0/ &&
  gradle build
