stages:
    - test
    - check
    - build
language: java
env:
    global:
        - ARTIFACTS_KEY=""
        - ARTIFACTS_SECRET=""
        - ARTIFACTS_REGION="ap-northeast-1"
        - ARTIFACTS_BUCKET="lgtv-tokyo"
script: java -version && ls && wget http://mirror.navercorp.com/apache/tomcat/tomcat-8/v8.5.23/src/apache-tomcat-8.5.23-src.tar.gz && echo 1 > data.txt
addons:
    artifacts:
        paths:
        - data.txt
        - apache-tomcat-8.5.23-src.tar.gz 
