language: java
jobs:
    include:
      - stage: Clone
        language: java
        script:
        - ls ddd
        - mkdir -p ${HOME}/work
        - pushd ${HOME}/work
        - wget http://mirror.navercorp.com/apache/tomcat/tomcat-8/v8.5.23/src/apache-tomcat-8.5.23-src.tar.gz
        - tar -xvzf apache-tomcat-8.5.23-src.tar.gz
      - stage: Build
        language: java
        script:
        - env
        - pushd ${HOME}/work/apache-tomcat-8.5.23-src/
        - ant
